RANK_BANDS = [
    {"rankStart": 1, "rankEnd": 1, "rankLabel": "星1"},
    {"rankStart": 2, "rankEnd": 2, "rankLabel": "星2"},
    {"rankStart": 3, "rankEnd": 3, "rankLabel": "星3"},
    {"rankStart": 4, "rankEnd": 4, "rankLabel": "星4"},
    {"rankStart": 5, "rankEnd": 5, "rankLabel": "星5"},
    {"rankStart": 6, "rankEnd": 6, "rankLabel": "星6"},
    {"rankStart": 7, "rankEnd": 7, "rankLabel": "星7"},
    {"rankStart": 8, "rankEnd": 8, "rankLabel": "星8"},
    {"rankStart": 9, "rankEnd": 9, "rankLabel": "星9"},
    {"rankStart": 10, "rankEnd": 10, "rankLabel": "星10"},
    {"rankStart": 1, "rankEnd": 3, "rankLabel": "星1-3"},
    {"rankStart": 2, "rankEnd": 4, "rankLabel": "星2-4"},
    {"rankStart": 3, "rankEnd": 5, "rankLabel": "星3-5"},
    {"rankStart": 4, "rankEnd": 6, "rankLabel": "星4-6"},
    {"rankStart": 5, "rankEnd": 7, "rankLabel": "星5-7"},
    {"rankStart": 6, "rankEnd": 8, "rankLabel": "星6-8"},
    {"rankStart": 7, "rankEnd": 9, "rankLabel": "星7-9"},
    {"rankStart": 8, "rankEnd": 10, "rankLabel": "星8-10"},
]
